// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pricing.DataAccess.PostgreSql;

namespace Pricing.DataAccess.PostgreSql.Migrations
{
    [DbContext(typeof(DomainModelPostgreSqlContext))]
    partial class DomainModelPostgreSqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Pricing.Domain.Price", b =>
                {
                    b.Property<long>("PriceId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AgeFrom");

                    b.Property<int>("AgeTo");

                    b.Property<decimal>("Rate");

                    b.Property<long?>("TarrifId");

                    b.Property<DateTime>("UpdatedTimestamp");

                    b.HasKey("PriceId");

                    b.HasIndex("TarrifId");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("Pricing.Domain.Tarrif", b =>
                {
                    b.Property<long>("TarrifId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ProductCode");

                    b.Property<DateTime>("UpdatedTimestamp");

                    b.HasKey("TarrifId");

                    b.ToTable("Tarrifs");
                });

            modelBuilder.Entity("Pricing.Domain.Price", b =>
                {
                    b.HasOne("Pricing.Domain.Tarrif", "Tarrif")
                        .WithMany("Prices")
                        .HasForeignKey("TarrifId");
                });
#pragma warning restore 612, 618
        }
    }
}
