FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app
#http
EXPOSE 5100
#https
EXPOSE 5101

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY src/ApiGateways/MicroDemo.Api/MicroDemo.Api.csproj src/ApiGateways/MicroDemo.Api/
COPY src/Core/Messages/Messages.csproj src/Core/Messages/
COPY src/Core/Common/Common.csproj src/Core/Common/
COPY src/Core/EventBus/EventBus.csproj src/Core/EventBus/
RUN dotnet restore src/ApiGateways/MicroDemo.Api/MicroDemo.Api.csproj
#COPY . .
WORKDIR /src/src/ApiGateways/MicroDemo.Api
RUN dotnet build MicroDemo.Api.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish MicroDemo.Api.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "MicroDemo.Api.dll"]
